CC = gcc
CFLAGS = -Wall -O2 -fPIC -m32
LDFLAGS = -shared -m32
TARGET = tgLogLib.so
SRCS = tgLogLib_mqtt.c tgLogLib_rest.c tgLogLib_mysql.c tgLogLib_influxdb.c
OBJS = $(SRCS:.c=.o)

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CC) $(LDFLAGS) -o $@ $^

%.o: %.c tgLogLib.h
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJS) $(TARGET)
